# Generated by Django 4.1.2 on 2022-11-10 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("grafs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_id", models.IntegerField(unique=True)),
                ("platform", models.CharField(max_length=255)),
                ("deviceType", models.CharField(max_length=255)),
                ("eventName", models.CharField(max_length=255)),
                ("language", models.CharField(max_length=255)),
                ("referrer", models.CharField(max_length=255)),
                ("localTime", models.TimeField()),
                ("date", models.DateField()),
                ("loadTime", models.TimeField()),
                ("timeFromStart", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SubUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_id", models.IntegerField(unique=True)),
                ("platformUserId", models.IntegerField(unique=True)),
                ("sessionCounter", models.IntegerField()),
                ("playTime", models.IntegerField()),
                ("active", models.BooleanField(default=False)),
                ("lastActivity", models.IntegerField()),
                ("referer", models.CharField(max_length=255)),
                ("registrationDate", models.DateField()),
                ("adsCounter", models.IntegerField()),
                ("platform", models.CharField(max_length=255)),
                ("deviseType", models.CharField(max_length=255)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="grafs.event"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_id", models.IntegerField(unique=True)),
                ("versionIdentifier", models.CharField(max_length=255)),
                ("platform", models.CharField(max_length=255)),
                ("startTime", models.TimeField()),
                ("startDate", models.DateField()),
                ("startDateLong", models.IntegerField()),
                ("endTime", models.TimeField()),
                ("endDate", models.DateField()),
                ("endDateLong", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Person",
        ),
    ]
