# Generated by Django 4.1.2 on 2022-11-10 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grafs", "0002_event_subuser_version_delete_person"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="date",
        ),
        migrations.RemoveField(
            model_name="event",
            name="loadTime",
        ),
        migrations.RemoveField(
            model_name="event",
            name="localTime",
        ),
    ]
