# Generated by Django 4.1.2 on 2022-11-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grafs", "0006_alter_event_date_alter_event_localtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="deviceType",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="eventName",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="language",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="loadTime",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="platform",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="referrer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="timeFromStart",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subuser",
            name="active",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="subuser",
            name="adsCounter",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subuser",
            name="deviseType",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="subuser",
            name="lastActivity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subuser",
            name="platform",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="subuser",
            name="playTime",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subuser",
            name="referer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="subuser",
            name="registrationDate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subuser",
            name="sessionCounter",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="version",
            name="endDate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="version",
            name="endDateLong",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="version",
            name="endTime",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="version",
            name="startDate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="version",
            name="startDateLong",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="version",
            name="startTime",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
