version: "3.11"

services:
  redis:
    image: redis
    restart: always
    ports: 
      - "6379:6379"
    networks:
      - back
  
  webapp:
    restart: always
    build: 
      context: ./webapp
    ports: 
      - "15680:15680"
    command: [ "python3", "./gamestatistics/manage.py", "runserver", "0.0.0.0:15680"]
    networks:
      - back
  
  worker:
    restart: always
    build: 
      context: ./webapp
    volumes: 
      - ./data:/app/data/
    command: ['celery', '--workdir=./gamestatistics', '-A', 'gamestatistics', 'worker' ]
    networks:
      - back

  beat:
    restart: always
    build: 
      context: ./webapp
    volumes: 
      - ./data:/app/data/
    command: ['celery', '--workdir=./gamestatistics', '-A', 'gamestatistics', 'beat' ]
    networks:
      - back
    
networks:
  back:
