version: "3.11"

services:
  redis:
    image: redis
    restart: always
    ports: 
      - "6379:6379"
  
  webapp:
    restart: always
    build: 
      context: ./webapp
    ports: 
      - "8000:8000"
    command: [ "python3", "./gamestatistics/manage.py", "runserver", "0.0.0.0:8000"]
  
  worker:
    restart: always
    build: 
      context: ./webapp
    volumes: 
      - ./data:/app/data/
    command: ['celery', '--workdir=./gamestatistics', '-A', 'gamestatistics', 'worker' ]

  beat:
    restart: always
    build: 
      context: ./webapp
    volumes: 
      - ./data:/app/data/
    command: ['celery', '--workdir=./gamestatistics', '-A', 'gamestatistics', 'beat' ]