# Generated by Django 4.1.2 on 2022-11-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grafs", "0004_event_date_event_loadtime_event_localtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="loadTime",
            field=models.CharField(max_length=255),
        ),
    ]
