# Generated by Django 4.1.2 on 2022-11-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grafs", "0005_alter_event_loadtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="localTime",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
