# Generated by Django 4.1.2 on 2022-11-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grafs", "0008_alter_event_sub_id_alter_subuser_platformuserid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subuser",
            name="event",
        ),
        migrations.AddField(
            model_name="subuser",
            name="event",
            field=models.ManyToManyField(to="grafs.event"),
        ),
    ]
